import Head from 'next/head'
import React from 'react'

import styles from '../styles/Home.module.css'
import Page from './components/Page'

const MemoizedContainer = React.memo(Page)

export default function Home() {

  return (
    <div className={styles.container} data-theme="business">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MemoizedContainer />
      </main>
    </div>
  )
}
