import Head from 'next/head'
import { HTML5Backend } from 'react-dnd-html5-backend'
import { DndProvider } from 'react-dnd'
import styles from '../styles/Home.module.css'
import { Artboard } from './components/Artboard'
import { Box } from './components/Box'
import React, { useState } from 'react'
import { ToolbarItem } from './components/ToolbarItem'

const Container = () => {
  const [boxes, setBoxes] = useState({})

  const ToolbarItems = {
    a: { title: 'Image', top: 0, left: 0 },
    b: { title: 'Button', top: 0, left: 0 },
    c: { title: 'Date', top: 0, left: 0 },
    d: { title: 'Text', top: 0, left: 0 }
  }

  return (
    <div className="flex min-h-screen">
      <DndProvider backend={HTML5Backend}>
        <aside className="flex-1 w-1/5 py-8 px-4 bg-slate-900">
          <h3>Menu</h3>
          <nav className="flex flex-col">
            {Object.keys(ToolbarItems).map((key) => {
              const { left, top, title } = ToolbarItems[key]
              
              return (
                <ToolbarItem
                  key={key}
                  title={title}
                  setBox={() => {
                    setBoxes(boxes => ({
                      ...boxes,
                      [key]: { left, top, title}
                    }))
                  }}
                />
              )
            })} 
          </nav>
        </aside>
        <main className="w-4/5">
          <Artboard boxes={boxes} setBoxes={setBoxes} />
        </main>
      </DndProvider>
    </div>
  )
}

const MemoizedContainer = React.memo(Container)

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <MemoizedContainer />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
